import { useEffect, useMemo, useRef, useState } from 'react';
import { Download, ImageIcon, ImagePlus } from 'lucide-react';
import PageHeader from '@/components/PageHeader';
import TypePills from '@/components/TypePills';
import { copy, cvdTypes } from '@/data/appData';
import { useAppStore } from '@/store/appStore';
import { drawComparisonCanvases, getContainedSize, simulateImageData } from '@/utils/colorVision';

export default function ImagePage() {
  const language = useAppStore((state) => state.language);
  const imageType = useAppStore((state) => state.imageType);
  const setImageType = useAppStore((state) => state.setImageType);
  const text = copy[language];
  const originalRef = useRef<HTMLCanvasElement | null>(null);
  const simulatedRef = useRef<HTMLCanvasElement | null>(null);
  const [imageSrc, setImageSrc] = useState<string>('');
  const [imageName, setImageName] = useState('');
  const [renderSize, setRenderSize] = useState({ width: 0, height: 0 });
  const typeMeta = useMemo(() => cvdTypes.find((item) => item.key === imageType), [imageType]);

  useEffect(() => {
    const originalCanvas = originalRef.current;
    const simulatedCanvas = simulatedRef.current;
    if (!originalCanvas || !simulatedCanvas || !imageSrc) {
      return;
    }

    drawComparisonCanvases(imageSrc, originalCanvas, simulatedCanvas, imageType)
      .then(setRenderSize)
      .catch(() => setRenderSize({ width: 0, height: 0 }));
  }, [imageSrc, imageType]);

  function handleFileChange(event: React.ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0];
    if (!file) {
      return;
    }

    const reader = new FileReader();
    reader.onload = () => {
      setImageSrc(String(reader.result));
      setImageName(file.name);
    };
    reader.readAsDataURL(file);
  }

  async function exportReport() {
    const originalCanvas = originalRef.current;
    const simulatedCanvas = simulatedRef.current;
    if (!originalCanvas || !simulatedCanvas || !renderSize.width || !renderSize.height || !imageSrc) {
      return;
    }

    const reportCanvas = document.createElement('canvas');
    const context = reportCanvas.getContext('2d');
    if (!context) {
      return;
    }

    const sourceImage = await loadReportImage(imageSrc);
    const cardImageSize = getContainedSize(sourceImage.width, sourceImage.height, 764);
    const baseCanvas = document.createElement('canvas');
    const baseContext = baseCanvas.getContext('2d');
    if (!baseContext) {
      return;
    }

    baseCanvas.width = cardImageSize.width;
    baseCanvas.height = cardImageSize.height;
    baseContext.drawImage(sourceImage, 0, 0, cardImageSize.width, cardImageSize.height);

    const baseImageData = baseContext.getImageData(0, 0, cardImageSize.width, cardImageSize.height);
    const reportItems = [
      {
        title: text.image.original,
        description: language === 'zh' ? '正常视觉效果' : 'Normal vision effect',
        canvas: baseCanvas,
      },
      ...cvdTypes
        .filter((item) => item.key !== 'normal')
        .map((item) => {
          const outputCanvas = document.createElement('canvas');
          outputCanvas.width = cardImageSize.width;
          outputCanvas.height = cardImageSize.height;
          const outputContext = outputCanvas.getContext('2d');
          if (!outputContext) {
            throw new Error('Canvas context is not available');
          }
          outputContext.putImageData(simulateImageData(baseImageData, item.key), 0, 0);
          return {
            title: item.names[language],
            description: item.descriptions[language],
            canvas: outputCanvas,
          };
        }),
    ];
    const reportTitle = language === 'zh' ? '无障碍报告' : 'Accessibility Report';
    const reportDescription = language === 'zh'
      ? '这些模拟展示了有各种视觉障碍的用户是如何感知您的设计，使用本报告来识别低对比度区域或颜色障碍问题。'
      : 'These simulations show how users with different visual impairments perceive your design. Use this report to identify low-contrast areas and color accessibility issues.';
    const generatedText = language === 'zh'
      ? `由 CVT 生成  生成时间 ${formatReportTime(language)}`
      : `Generated by CVT  Generated at ${formatReportTime(language)}`;
    const cardPositions = [
      { x: 40, y: 280 },
      { x: 876, y: 280 },
      { x: 1712, y: 280 },
      { x: 2548, y: 280 },
      { x: 40, y: 1244 },
      { x: 876, y: 1244 },
      { x: 1712, y: 1244 },
    ];

    reportCanvas.width = 3400;
    reportCanvas.height = 2360;
    context.textBaseline = 'top';
    context.textAlign = 'left';

    context.fillStyle = '#F7F7F4';
    context.fillRect(0, 0, reportCanvas.width, reportCanvas.height);
    context.fillStyle = '#141413';
    context.font = language === 'zh' ? '700 88px Songti TC, serif' : '700 80px Georgia, serif';
    context.fillText(reportTitle, 41, 41);
    context.fillStyle = '#8E8B82';
    context.font = '400 32px PingFang SC, Inter, sans-serif';
    drawWrappedText(context, reportDescription, 41, 184, 1568, 45);

    for (const [index, item] of reportItems.entries()) {
      const position = cardPositions[index];
      if (!position) {
        continue;
      }

      drawReportCard(context, {
        x: position.x,
        y: position.y,
        title: item.title,
        description: item.description,
        canvas: item.canvas,
      });
    }

    context.fillStyle = '#8E8B82';
    context.font = '400 24px PingFang SC, Inter, sans-serif';
    context.fillText(generatedText, 41, 2244);

    const link = document.createElement('a');
    link.href = reportCanvas.toDataURL('image/png');
    link.download = `${imageName.replace(/\.[^.]+$/, '')}-accessibility-report.png`;
    link.click();
  }

  return (
    <div className="space-y-6">
      <PageHeader eyebrow="Image Mode" title={text.image.title} body={text.image.body} />

      <section className="grid gap-6">
        <div className="theme-card bg-transparent p-5">
          <div className="flex items-center gap-3">
            <div className="flex h-12 w-12 items-center justify-center rounded-none bg-[#f4efe7] text-[#d6643e]">
              <ImageIcon className="h-5 w-5" />
            </div>
            <div>
              <p className="theme-kicker">Simulate</p>
              <h2 className="font-serif text-2xl font-semibold tracking-tight text-stone-900">
                {typeMeta?.names[language]}
                <span className="ml-2 align-middle font-sans text-sm font-normal tracking-normal text-stone-600">
                  {typeMeta?.descriptions[language]}
                  {typeMeta?.prevalence ? ` · ${typeMeta.prevalence[language]}` : ''}
                </span>
              </h2>
            </div>
          </div>

          <div className="mt-5">
            <TypePills language={language} value={imageType} onChange={setImageType} />
          </div>

          <div className="mt-6 grid gap-3 sm:grid-cols-2">
            <label className="inline-flex cursor-pointer items-center justify-center gap-2 rounded-none bg-[#d6643e] px-4 py-3 text-sm font-semibold text-stone-50 transition hover:bg-[#b95a38]">
              <ImagePlus className="h-4 w-4" />
              {text.common.uploadImage}
              <input type="file" accept="image/*" className="hidden" onChange={handleFileChange} />
            </label>
            <button
              type="button"
              onClick={exportReport}
              disabled={!renderSize.width || !renderSize.height}
              className={[
                'inline-flex items-center justify-center gap-2 rounded-none px-4 py-3 text-sm font-semibold transition',
                !renderSize.width || !renderSize.height
                  ? 'cursor-not-allowed bg-[#F7F7F4] text-[#C3C3C3]'
                  : 'bg-[#d6643e] text-white hover:bg-[#b95a38]',
              ].join(' ')}
            >
              <Download className="h-4 w-4" />
              {text.common.exportReport}
            </button>
          </div>
        </div>

        <div className="grid gap-5 md:grid-cols-2">
          {[text.image.original, typeMeta?.names[language] || ''].map((title, index) => (
            <article key={title} className="theme-card bg-transparent p-5">
              <div className="mb-4 flex items-center justify-between gap-3">
                <h3 className="font-serif text-2xl font-semibold tracking-tight text-stone-900">{title}</h3>
                {renderSize.width > 0 ? (
                  <span className="rounded-none bg-[#F7F7F4] px-3 py-1 text-xs font-semibold text-stone-500">
                    {renderSize.width} x {renderSize.height}
                  </span>
                ) : null}
              </div>
              <div className="flex aspect-square w-full items-center justify-center rounded-none border theme-card-border bg-[#f7f7f4] p-4">
                {imageSrc ? (
                  <canvas ref={index === 0 ? originalRef : simulatedRef} className="max-h-[560px] max-w-full rounded-none" />
                ) : (
                  <p className="w-full text-center text-sm text-stone-500">{text.common.emptyImage}</p>
                )}
              </div>
            </article>
          ))}
        </div>
      </section>
    </div>
  );
}

function drawReportCard(
  context: CanvasRenderingContext2D,
  options: {
    x: number;
    y: number;
    title: string;
    description: string;
    canvas: HTMLCanvasElement;
  },
) {
  const { x, y, title, description, canvas } = options;
  const outerWidth = 812;
  const outerHeight = 940;
  const imageFrameSize = 764;
  const padding = 24;
  const imageFrameX = x + padding;
  const imageFrameY = y + padding;

  context.fillStyle = '#FFFFFF';
  context.fillRect(x, y, outerWidth, outerHeight);

  context.strokeStyle = 'rgba(0, 0, 0, 0.08)';
  context.lineWidth = 1;
  context.strokeRect(imageFrameX + 0.5, imageFrameY + 0.5, imageFrameSize - 1, imageFrameSize - 1);

  const imageX = imageFrameX + (imageFrameSize - canvas.width) / 2;
  const imageY = imageFrameY + (imageFrameSize - canvas.height) / 2;
  context.drawImage(canvas, imageX, imageY, canvas.width, canvas.height);

  context.fillStyle = '#141413';
  context.font = '600 32px PingFang SC, Inter, sans-serif';
  context.fillText(title, x + padding, y + 812);

  context.fillStyle = '#8E8B82';
  context.font = '400 24px PingFang SC, Inter, sans-serif';
  drawWrappedText(context, description, x + padding, y + 860, imageFrameSize, 34);
}

function drawWrappedText(
  context: CanvasRenderingContext2D,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  lineHeight: number,
) {
  const paragraphs = text.split('\n');
  let currentY = y;

  for (const paragraph of paragraphs) {
    const words = /[\u4e00-\u9fff]/.test(paragraph) ? paragraph.split('') : paragraph.split(' ');
    let line = '';

    for (const token of words) {
      const nextLine = line ? `${line}${/[\u4e00-\u9fff]/.test(paragraph) ? '' : ' '}${token}` : token;
      if (context.measureText(nextLine).width > maxWidth && line) {
        context.fillText(line, x, currentY);
        line = token;
        currentY += lineHeight;
      } else {
        line = nextLine;
      }
    }

    if (line) {
      context.fillText(line, x, currentY);
      currentY += lineHeight;
    }
  }
}

function loadReportImage(src: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const image = new Image();
    image.onload = () => resolve(image);
    image.onerror = () => reject(new Error('Image failed to load'));
    image.src = src;
  });
}

function formatReportTime(language: 'zh' | 'en') {
  return new Intl.DateTimeFormat(language === 'zh' ? 'zh-CN' : 'en-US', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: language === 'zh',
  }).format(new Date());
}
